import React,{useState}from"react";import{createRoot}from"react-dom/client";import{Home,Users,Mic,BookOpen,UserRound,Lock,ChevronRight,CalendarDays}from"lucide-react";import"./style.css";
const rooms=[["은호네 독서모임","어린 왕자",43,"17~19쪽"],["가족 책방","데미안",28,"4~6쪽"],["성당 천사부","아낌없이 주는 나무",67,"10~12쪽"]];
function App(){const[v,setV]=useState("home"),[room,setRoom]=useState(rooms[0]);return <div className="app"><main><header><b>쪽<span>GO</span></b><i>☰</i></header>{v=="home"&&<HomeP setV={setV} open={r=>{setRoom(r);setV("room")}}/>}{v=="rooms"&&<Rooms setV={setV} open={r=>{setRoom(r);setV("room")}}/>}{v=="room"&&<Room r={room} setV={setV}/>} {v=="my"&&<My/>}</main><nav><N i={<Home/>} t="홈" f={()=>setV("home")}/><N i={<Users/>} t="함께 읽기방" f={()=>setV("rooms")}/><button className="mic" onClick={()=>alert("다음 단계에서 실제 녹음 서버 저장을 연결해요.")}><Mic/></button><N i={<BookOpen/>} t="내 서재"/><N i={<UserRound/>} t="MY 쪽GO" f={()=>setV("my")}/></nav></div>}
const N=({i,t,f})=><button onClick={f}>{i}<small>{t}</small></button>;
function HomeP({setV,open}){return <><section className="hero"><div><h1>한 쪽씩,<br/>함께 GO.</h1><p>오늘, 당신의 목소리로<br/>한 쪽을 이어주세요.</p></div><div>📖🌿</div></section><div className="quick"><button className="green"><Mic/><b>오늘 한 쪽 읽기</b><small>공개 책에 참여하기</small></button><button onClick={()=>setV("rooms")}><Users/><b>함께 읽기방 만들기</b><small>우리만의 책 만들기</small></button></div><button className="join" onClick={()=>setV("rooms")}><Lock/> 초대 코드로 방 입장하기</button><h3>지금 가장 많이 읽히는 책</h3><div className="books">{[["어린 왕자",73],["데미안",58],["아낌없이 주는 나무",67]].map(x=><div><div className="cover">📖</div><b>{x[0]}</b><strong>{x[1]}%</strong><Progress p={x[1]}/></div>)}</div><h3>나의 읽기 현황</h3><Calendar/><h3>참여 중인 방</h3><Card r={rooms[0]} f={()=>open(rooms[0])}/></>}
function Progress({p}){return <div className="bar"><i style={{width:p+"%"}}/></div>}
function Card({r,f}){return <button className="card" onClick={f}><div className="thumb">📖</div><span><b>{r[0]} 🔒</b><small>{r[1]} · 7명 참여</small><Progress p={r[2]}/></span><strong>{r[2]}%</strong><ChevronRight/></button>}
function Rooms({setV,open}){return <><h1>함께 읽기방</h1><div className="tabs">참여 중인 방　　내가 만든 방</div>{rooms.map(r=><Card r={r} f={()=>open(r)}/>)}<button className="wide">+ 함께 읽기방 만들기</button><button className="join"><Lock/> 초대 코드로 방 입장하기</button></>}
function Room({r,setV}){return <><button className="back" onClick={()=>setV("rooms")}>‹ 돌아가기</button><section className="room"><div className="thumb big">📖</div><div><h2>{r[0]} 🔒</h2><b>{r[1]}</b><p>7명 참여 · 함께 읽는 중</p></div></section><Progress p={r[2]}/><h3>페이지 배정</h3>{[["지현","17~19쪽"],["은호","20~22쪽"],["지호","23~25쪽"]].map(x=><div className="assign"><b>{x[0]}</b><span>{x[1]} ›</span></div>)}<div className="due"><CalendarDays/> <span>내 차례　<b>{r[3]}</b><br/>9월 12일까지</span></div><h3>최근 낭독</h3><div className="recent">▶　지현님이 17쪽을 낭독했어요</div><button className="wide"><Mic/> 내 낭독 시작하기</button></>}
function Calendar(){return <div className="cal">{["월","화","수","목","금","토","일"].map(x=><b>{x}</b>)}{[11,12,13,14,15,16,17].map((x,i)=><span className={i==1?"done":i==4?"doing":""}>{x}</span>)}</div>}
function My(){return <><h1>MY 쪽GO</h1><h3>이번 달 나의 읽기</h3><div className="stats"><div>시작 전<b>2권</b></div><div>읽는 중<b>3권</b></div><div>읽기 완료<b>1권</b></div></div><h3>나의 읽기 달력</h3><Calendar/><div className="due"><CalendarDays/><span><b>9월 12일까지</b><br/>17~19쪽 읽어주세요.</span></div><h3>참여 중인 방</h3><Card r={rooms[0]}/></>}
createRoot(document.getElementById("root")).render(<App/>);